# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: resume-website
spec:
  selector:
    app: resume-website
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

